# Generated by Django 4.1.7 on 2023-03-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('T', 'استاد'), ('S', 'دانشجو')], default='S', max_length=2, verbose_name='نقش کاربری'),
        ),
    ]
