# Generated by Django 4.1.7 on 2023-03-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='status',
            field=models.CharField(choices=[('ACC', 'تایید شده'), ('REJ', 'رد شده'), ('PEN', 'در حال بررسی')], default='PEN', max_length=3, verbose_name='وضعیت'),
        ),
    ]
