# Generated by Django 4.1.7 on 2023-03-10 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_thesis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_thesises', to=settings.AUTH_USER_MODEL, verbose_name='استاد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thesis',
            name='refree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refree_thesises', to=settings.AUTH_USER_MODEL, verbose_name='داور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('T', 'teacher'), ('S', 'student')], default='S', max_length=2, verbose_name='نقش کاربری'),
        ),
    ]
